import Head from "next/head";
import { Banner } from "../components/Banner/Banner";
import {
  Container,
  Grid,
  Title,
  createStyles,
  Text,
  List,
  Group,
  Divider,
  ThemeIcon,
  Accordion,
} from "@mantine/core";
const useStyles = createStyles((theme) => ({
  wrapper: {
    paddingTop: `calc(${theme.spacing.xl} * 2)`,
    paddingBottom: `calc(${theme.spacing.xl} * 2)`,
  },

  title: {
    marginBottom: `calc(${theme.spacing.xl} * 1.5)`,
  },

  item: {
    borderRadius: theme.radius.md,
    marginBottom: theme.spacing.lg,
    border: `1px solid ${
      theme.colorScheme === "dark" ? theme.colors.dark[4] : "#f0f0f0"
    }`,
  },
}));

export default function Faq() {
  const { classes } = useStyles();
  return (
    <>
      <Head>
        <title>Frequently Asked Questions | EFG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title="Frequently Asked Questions" />
      <Container size="md" mt={30} className={classes.wrapper}>
        <Accordion variant="separated">
          <Accordion.Item className={classes.item} value="2">
            <Accordion.Control>
              What types of safety courses do you offer?
            </Accordion.Control>
            <Accordion.Panel>
              We offer a wide range of safety courses tailored to various
              industries and needs. Our courses are WSQ and LSP approved. Visit{" "}
              <a href="/courses">our courses</a>.
            </Accordion.Panel>
          </Accordion.Item>
          <Accordion.Item className={classes.item} value="1">
            <Accordion.Control>
              How do I book a safety course?
            </Accordion.Control>
            <Accordion.Panel>
              To book a safety course, go to our website's{" "}
              <a href="/booking" target="_blank">
                booking page
              </a>
              and fill out the course booking form. Provide the required
              information such as your name, contact details, preferred course
              date, and any additional details if needed. Submit the form, and
              our team will contact you to confirm your booking. Otherwise you
              can <a href="tel:+6563347872">call us</a> or{" "}
              <a href="mailto:admin@efg.com.sg">email us</a> directly with your
              queries and our team will respond within 24hrs.
            </Accordion.Panel>
          </Accordion.Item>

          <Accordion.Item className={classes.item} value="3">
            <Accordion.Control>
              How can I check the schedule and availability of courses?
            </Accordion.Control>
            <Accordion.Panel>
              You can check the schedule and availability of courses on our
              website. Visit{" "}
              <a href="/schedule" target="_blank">
                schedule page
              </a>
              , and you'll find information about upcoming course dates,
              timings, and availability. If you have specific requirements or
              need assistance, feel free to reach out to our team for
              personalized guidance.
            </Accordion.Panel>
          </Accordion.Item>

          <Accordion.Item className={classes.item} value="4">
            <Accordion.Control>
              Can I reschedule or cancel my booking?
            </Accordion.Control>
            <Accordion.Panel>
              Yes, you can reschedule or cancel your booking, but please note
              that it is subject to our rescheduling and cancellation policy.
              Contact our support team or refer to our booking terms and
              conditions for detailed information on rescheduling and
              cancellation procedures.
            </Accordion.Panel>
          </Accordion.Item>

          <Accordion.Item className={classes.item} value="7">
            <Accordion.Control>
              Can companies or organizations book safety courses for their
              employees?
            </Accordion.Control>
            <Accordion.Panel>
              Absolutely! We offer corporate booking options for companies and
              organizations looking to provide safety training for their
              employees. Our team can customize the training programs to meet
              specific organizational needs and deliver the courses at your
              preferred location or our training facility.
            </Accordion.Panel>
          </Accordion.Item>
          <Accordion.Item className={classes.item} value="11">
            <Accordion.Control>
              What items should be brought when attending the class?
            </Accordion.Control>
            <Accordion.Panel>
              <ul>
                <li>Please bring a copy of your NRIC/WP/IPA/S Pass/E Pass.</li>
                <li>
                  Safety shoes are required on the second day of the course.
                </li>
                <li>
                  Make sure to bring any valid ID card with your photograph.
                </li>
                <li>
                  Please bring the necessary payment for the course if it is
                  still pending.
                </li>
              </ul>
            </Accordion.Panel>
          </Accordion.Item>

          <Accordion.Item className={classes.item} value="8">
            <Accordion.Control>
              Are your instructors qualified and experienced?
            </Accordion.Control>
            <Accordion.Panel>
              Yes, our instructors are highly qualified and experienced in their
              respective fields. They possess the necessary certifications,
              expertise, and practical knowledge to deliver effective safety
              training. Rest assured, you will be learning from professionals
              who are committed to providing quality education and ensuring your
              understanding of safety practices.
            </Accordion.Panel>
          </Accordion.Item>

          <Accordion.Item className={classes.item} value="50">
            <Accordion.Control>
              When can I collect the course completion card (pass)?
            </Accordion.Control>
            <Accordion.Panel>
              Upon successfully completing the course and passing the exam, the
              collection of the safety pass differs based on the level:
              <ul>
                <li>
                  For workers, the safety pass can be collected on the last day
                  of the course. The card will remain valid until the specified
                  expiration date.
                </li>
                <li>
                  For supervisors, the safety pass can be collected three days
                  after the course has finished. The card will also be valid
                  until the specified expiration date.
                </li>
              </ul>
            </Accordion.Panel>
          </Accordion.Item>

          <Accordion.Item className={classes.item} value="10">
            <Accordion.Control>
              What payment methods are available for booking?
            </Accordion.Control>
            <Accordion.Panel>
              We offer the following payment methods for booking:
              <ul>
                <li>PayNow</li>
                <li>Bank Transfer</li>
                <li>GIRO</li>
                <li>Cash</li>
                <li>Cheque</li>
              </ul>
            </Accordion.Panel>
          </Accordion.Item>
          <Accordion.Item className={classes.item} value="11">
            <Accordion.Control>
              Are there any discounts or promotions available for course
              bookings?
            </Accordion.Control>
            <Accordion.Panel>
              We periodically offer discounts, promotions, or special offers on
              our safety courses. Keep an eye on our website's promotions
              section or subscribe to our newsletter to stay updated on any
              upcoming discounts or promotional campaigns.
            </Accordion.Panel>
          </Accordion.Item>
        </Accordion>
      </Container>
    </>
  );
}
