import Head from "next/head";
import { FeaturesGrid } from "../components/Features/Features";
import { HeroHome } from "../components/HeroHome/HeroHome";
import { FeaturedCourseCard } from "../components/FeaturedCourseCard/FeaturedCourseCard";
import { HomeBannner } from "../components/HomeBannner/HomeBanner";
import { Container, Grid, Title, createStyles, Text } from "@mantine/core";
import { GetStaticProps } from "next";
import courses from "../public/jsons/courses.json";

const data = {
  title: "Integrate effortlessly with any technology stack",
  description:
    "Every once in a while, you’ll see a Golbat that’s missing some fangs. This happens when hunger drives it to try biting a Steel-type Pokémon.",
};

const useStyles = createStyles((theme) => ({
  wrapper: {
    paddingTop: theme.spacing.xl * 4,
    paddingBottom: theme.spacing.xl * 2,
  },

  title: {
    fontFamily: `Greycliff CF, ${theme.fontFamily}`,
    fontWeight: 900,
    marginBottom: theme.spacing.md,
    textAlign: "center",

    [theme.fn.smallerThan("sm")]: {
      fontSize: 28,
      textAlign: "left",
    },
  },

  description: {
    textAlign: "center",

    [theme.fn.smallerThan("sm")]: {
      textAlign: "left",
    },
  },
}));


export const getStaticProps: GetStaticProps = async () => {
  const playlistList = courses.data.pages.nodes.filter(
    (p, index) => index < 6
  );
  return {
    props: {
      courseList: playlistList,
    },
  };
};

type postData = {
  courseList: {
    databaseId: number,
    slug: string,
    title: string,
    uri: string,
    content: string | null,
    featuredImage?: {
      node?: {
        mediaItemurl: string
      }
    }
  }[]
};

export default function Home({courseList}: postData) {
  const { classes } = useStyles();
  const gridItems = courseList.map((item, index) => (
    <Grid.Col key={`FCC-${index}`} md={6} lg={4}>
      <FeaturedCourseCard title={item.title} link={item.uri} image={item.featuredImage && item.featuredImage.node && item.featuredImage.node.mediaItemurl} />
    </Grid.Col>
  ));

  return (
    <>
      <Head>
        <title>Create Next App R</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroHome />
      <Container size="lg" my={40}>
        <Title className={classes.title} mt={60} mb={40}>
          Courses on demand!
        </Title>

        {/* <Container size={560} p={0}>
          <Text size="sm" className={classes.description}>
            Some of our safety courses on high demand.
          </Text>
        </Container> */}
        <Grid gutter={40}>{gridItems}</Grid>
      </Container>
      <HomeBannner />
      <FeaturesGrid {...data} />
    </>
  );
}
