import { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import { Text, Title, Container } from "@mantine/core";
import styles from "../styles/Schedule.module.css";
import { Banner } from "../components/Banner/Banner";
import ClassCard from "../components/ClassCard/ClassCard";

type CourseSchedule = {
  courses: {
    courseName: string;
    courseId: number;
    courseSchedule: {
      classId: number;
      courseDate: string;
      availableSlots: number;
      session: string;
      timing: string;
      location: string;
    }[];
  }[];
};

const UsersPage: React.FC = () => {
  const [schedule, setSchedule] = useState<CourseSchedule | null>(null);

  useEffect(() => {
    fetchSchedule();
  }, []);

  const fetchSchedule = async () => {
    try {
      const response = await axios.get("../jsons/booking.json");
      const data = response.data as CourseSchedule;
      setSchedule(data);
      console.log(data);
    } catch (error) {
      console.error("Error fetching schedule:", error);
    }
  };

  if (schedule === null) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>About Us | EFG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title="Course Schedule" />
      <Container size="md" mt={60}>
        {schedule.courses.map((course, index) => (
          <div key={index} className={styles.courseContainer}>
            <Text size="xl" weight={700} style={{ marginBottom: "0.5rem" }}>
              {course.courseName}
            </Text>

            <div className={styles.scheduleContainer}>
              {course.courseSchedule.map((scheduleItem, scheduleIndex) => (
                <ClassCard
                  id={scheduleItem.classId}
                  courseDate={scheduleItem.courseDate}
                  availableSlots={scheduleItem.availableSlots}
                  session={scheduleItem.session}
                  timing={scheduleItem.timing}
                  location={scheduleItem.location}
                />
              ))}
            </div>
          </div>
        ))}
      </Container>
    </div>
  );
};

export default UsersPage;
