import { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import {
  Text,
  Anchor,
  NavLink,
  Container,
  Group,
  Divider,
} from "@mantine/core";
import styles from "../styles/Schedule.module.css";
import { Banner } from "../components/Banner/Banner";
import ClassCard from "../components/ClassCard/ClassCard";

type CourseSchedule = {
  courses: {
    courseName: string;
    courseId: number;
    courseSchedule: {
      classId: number;
      classDate: string;
      availableSlots: number;
      session: string;
      timing: string;
      location: string;
    }[];
  }[];
};

const UsersPage: React.FC = () => {
  const [schedule, setSchedule] = useState<CourseSchedule | null>(null);

  useEffect(() => {
    fetchSchedule();
  }, []);

  const currentDate = new Date();
  const year = currentDate.getFullYear();
  const month = String(currentDate.getMonth() + 1).padStart(2, "0");
  const day = String(currentDate.getDate()).padStart(2, "0");

  const formattedDate = `${year}-${month}-${day}`;

  const fetchSchedule = async () => {
    try {
      const response = await axios({
        method: "post",
        url: process.env.NEXT_PUBLIC_COURSE_SCHEDULE_API_URL,
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        data: {
          reqdate: formattedDate,
        },
      });
      const data = response.data as CourseSchedule;
      setSchedule(data);
    } catch (error) {
      console.error("Error fetching schedule:", error);
    }
  };

  if (schedule === null) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>Course Schedule | EFG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title="Course Schedule" />
      <Container size="md" mt={60}>
        {schedule.courses.map((course, index) => (
          <div key={index} className={styles.courseContainer}>
            <Group position="apart">
              <Text size="xl" weight={700} style={{ marginBottom: "0.5rem" }}>
                {course.courseName}
              </Text>
              <Anchor href={"/courses"}>Learn More</Anchor>
            </Group>

            <div className={styles.scheduleContainer}>
              {course.courseSchedule.map((scheduleItem, scheduleIndex) => (
                <ClassCard key={scheduleIndex} schedule={scheduleItem} />
              ))}
            </div>
          </div>
        ))}
      </Container>
    </div>
  );
};

export default UsersPage;
