import Head from "next/head";
import { Banner } from "../components/Banner/Banner";
import {
  Container,
  Grid,
  Card,
  Title,
  createStyles,
  Text,
  List,
  Group,
  Divider,
  ThemeIcon,
  Accordion,
} from "@mantine/core";
const useStyles = createStyles((theme) => ({
  wrapper: {
    paddingTop: `calc(${theme.spacing.xl} * 2)`,
    paddingBottom: `calc(${theme.spacing.xl} * 2)`,
  },

  title: {
    marginBottom: `calc(${theme.spacing.xl} * 1.5)`,
  },

  item: {
    borderRadius: theme.radius.md,
    marginBottom: theme.spacing.lg,
    border: `1px solid ${
      theme.colorScheme === "dark" ? theme.colors.dark[4] : "#f0f0f0"
    }`,
  },
}));

export default function Faq() {
  const { classes } = useStyles();
  return (
    <>
      <Head>
        <title>Terms and Conditions | EFG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner title="Terms and Conditions" />
      <Container size="sm" mt={30} className={classes.wrapper}>
        By booking with us, you agree to the following terms and conditions:
        <List type="ordered" m={20} spacing="xs" withPadding>
          <List.Item>
            All payment can be made by crossed cheque payable to EFG Training
            Services Private Ltd.
          </List.Item>
          <List.Item>
            Payment should be made on or before the course date to take the
            exam.
          </List.Item>
          <List.Item>
            If payment is not received, the printing of the ID PASS /
            Certificate will not be possible.
          </List.Item>
          <List.Item>
            Credit Terms: 8% will be charged if payment is not received on or
            before the course date.
          </List.Item>
          <List.Item>
            No Amount Will Be Refunded, If They Fail To Attend The Course On The
            Commencement Date or Attend The Course And Discontinued Mid-Way
            Through The Course.
          </List.Item>
          <List.Item>For retake exam full course fee applies.</List.Item>
          <List.Item>
            Kindly take note Singaporeans &amp; PR if grant not approved by SSG
            must make full payment.
          </List.Item>
        </List>
        By proceeding, you acknowledge that you have read, understood, and
        agreed to comply with the above terms and conditions.
      </Container>
    </>
  );
}
